# Generated by Django 5.0.3 on 2024-12-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='items',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='items',
            field=models.ManyToManyField(related_name='grocery_lists', to='meal_planner.groceryitem'),
        ),
    ]
