# Generated by Django 5.0.3 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0002_groceryitem_remove_grocerylist_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='Unnamed List', max_length=255),
        ),
    ]
